mysql:
  dns: root:admin@tcp(localhost:3306)/heartbeat?charset=utf8mb4&parseTime=True&loc=Local
redis:
  addr: "192.168.6.128:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间   
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线 
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H
oss:
  Endpoint: "oss-cn-hangzhou.aliyuncs.com"
  AccessKeyId: "LTAI5tNCXPJwS3MstKoKgixh"
  AccessKeySecret: "YhHE8OyCMsqfjwOnxQ1oO7paYlDjVHX"
  Bucket : "heartbeat"
port:
  server: ":8082"
  udp: 3001